server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: mortgage-valuation-app
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Azure Configuration
azure:
  # Azure OpenAI Configuration
  openai:
    endpoint: ${OPENAI_API_ENDPOINT}
    api-key: ${OPENAI_API_KEY}
    deployment-name: gpt-4.1
    max-tokens: 4000
    temperature: 0.1
  # Azure Document Intelligence Configuration
  document-intelligence:
    endpoint: ${DOCUMENT_ANALYSER_ENDPOINT}
    api-key: ${DOCUMENT_ANALYSER_API_KEY}
  # Azure Storage Configuration
  storage:
    connection-string: ${AZURE_STORAGE_CONNECTION_STRING}
    container-name: lending-property
    valuation-reports-path: property-valuation-reports

# Application Configuration
app:
  valuation:
    pdf-path-template: "lnap4879/{requestId}/report.pdf"
    timeout-seconds: 300
    max-file-size-mb: 50

# Logging Configuration
logging:
  level:
    com.mortgage.valuation: DEBUG
    org.springframework.web: INFO
    software.amazon.awssdk: INFO
    com.azure: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/valuation-app.log
    max-size: 100MB
    max-history: 30

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev

aws:
  s3:
    endpoint: http://localhost:4566  # LocalStack for development

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    com.mortgage.valuation: INFO
    org.springframework.web: WARN
    software.amazon.awssdk: WARN
    com.azure: WARN
