version: '3.8'

services:
  # LocalStack for local S3 development
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack-data:/tmp/localstack"
    networks:
      - valuation-network

  # S3 bucket setup script
  setup-s3:
    image: amazon/aws-cli:latest
    depends_on:
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-west-2
    command: >
      sh -c "
        aws --endpoint-url=http://localstack:4566 s3 mb s3://mortgage-valuation-documents &&
        echo 'S3 bucket created successfully'
      "
    networks:
      - valuation-network

networks:
  valuation-network:
    driver: bridge

volumes:
  localstack-data:
